### ISSUE TITLE
docker-compose.yml file outdated

### ISSUE THREAD

**Issue by CraKy18** [peterjah/massa-core-docker#13]
When you install from fresh the docker-compose.yml its the outdated one without the MINIMAL_FEE variable, so basicly the auto buy rolls doesnt work

![image](https://github.com/user-attachments/assets/2b93b4c9-6fef-4a3c-bba5-d7cdaa0c07e2)

Perhaps update it to the new version that brings that new line with - MINIMAL_FEE=0

**Comment by peterjah** [comment]
if minimal fee is not set, it is 0 by default.
look at here:
https://github.com/peterjah/massa-core-docker/blob/f76ccf65a1b0abd1d09db987f8b139c5a60005b6/massa-guard.sh#L13

**Comment by CraKy18** [comment]
Weird cuz i freshly set up the repository on a new box and didn't give me the variable
I had to change and set it manually

**Comment by peterjah** [comment]
should be resolved with last version!
